'use strict';
const $ = id => document.getElementById(id);
const fmt = (value, digits=2) => value == null || !Number.isFinite(Number(value)) ? '—' : Number(value).toLocaleString('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits});
const money = value => value == null ? '—' : '$' + fmt(value);
const signed = value => value == null ? '—' : (Number(value)<0?'−':'+') + '$' + fmt(Math.abs(Number(value)));
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svgNS = 'http://www.w3.org/2000/svg';
let current = 'demo', snapshot = null, bookSide = 'Up', fillFilter = 'All', polling = false, wallet = null;
async function api(path, body) {const response=await fetch(path, body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}); const data=await response.json(); if(!response.ok)throw Error(data.error||`HTTP ${response.status}`); return data;}
function set(id, value) {$(id).textContent=value;}
function timeLabel(ts, demo=false) {return demo?`${Math.floor(ts/60)}:${String(Math.floor(ts%60)).padStart(2,'0')}`:new Date(ts*1000).toLocaleTimeString('en-GB',{timeZone:'UTC'});}
function isDemo() {return snapshot?.report?.source?.includes('synthetic');}
function chart(id, rows, series, options={}) {
 const container=$(id); const valid=rows.filter(r=>series.some(s=>r[s.key]!=null && Number.isFinite(Number(r[s.key]))));
 if(!valid.length){container.innerHTML='<div class="empty-chart">No observations yet</div>';return;}
 const width=Math.max(280,container.clientWidth), height=Math.max(45,container.clientHeight), spark=options.spark, margin=spark?{l:0,r:0,t:4,b:3}:{l:44,r:10,t:12,b:25};
 const values=valid.flatMap(r=>series.map(s=>r[s.key]).filter(v=>v!=null).map(Number)); let low=options.min??Math.min(...values), high=options.max??Math.max(...values);
 if(!options.fixed){const padding=(high-low||Math.max(Math.abs(high)*.002,1))*.15; low-=padding;high+=padding;}
 const first=valid[0].ts,last=valid.at(-1).ts, x=ts=>margin.l+(ts-first)/Math.max(.001,last-first)*(width-margin.l-margin.r),y=v=>height-margin.b-(v-low)/Math.max(.000001,high-low)*(height-margin.t-margin.b);
 let markup=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(container.parentElement.querySelector('h2')?.textContent||'P&L trend')}">`;
 if(!spark){for(let i=0;i<4;i++){const value=low+(high-low)*i/3, yy=y(value);markup+=`<line class="grid" x1="${margin.l}" x2="${width-margin.r}" y1="${yy}" y2="${yy}"/><text x="${margin.l-6}" y="${yy+3}" text-anchor="end">${options.percent?Math.round(value*100)+'%':fmt(value,options.digits??1)}</text>`;} for(const ts of [first,(first+last)/2,last])markup+=`<text x="${x(ts)}" y="${height-5}" text-anchor="${ts===first?'start':ts===last?'end':'middle'}">${timeLabel(ts,isDemo())}</text>`;}
 series.forEach((s,index)=>{let d='',inSegment=false;for(const r of valid){if(r[s.key]==null){inSegment=false;continue;}d+=(inSegment?'L':'M')+x(r.ts).toFixed(2)+','+y(Number(r[s.key])).toFixed(2);inSegment=true;}
 if(options.area&&index===0){const points=valid.filter(r=>r[s.key]!=null);if(points.length){markup+=`<defs><linearGradient id="fade-${id}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${s.color}" stop-opacity=".18"/><stop offset="1" stop-color="${s.color}" stop-opacity="0"/></linearGradient></defs><path d="${d}L${x(points.at(-1).ts)},${height-margin.b}L${x(points[0].ts)},${height-margin.b}Z" fill="url(#fade-${id})"/>`;}}
 markup+=`<path class="series" d="${d}" stroke="${s.color}" ${s.dash?'stroke-dasharray="4 4"':''}/>`;});
 if(!spark)markup+=`<rect class="chart-hit" x="${margin.l}" y="${margin.t}" width="${width-margin.l-margin.r}" height="${height-margin.t-margin.b}" fill="transparent"/>`;
 container.innerHTML=markup+'</svg>';
 const hit=container.querySelector('.chart-hit');if(hit){hit.addEventListener('pointermove',event=>{const box=container.getBoundingClientRect(), ts=first+((event.clientX-box.left-margin.l)/(width-margin.l-margin.r))*(last-first);const row=valid.reduce((a,b)=>Math.abs(b.ts-ts)<Math.abs(a.ts-ts)?b:a); showTip(event,timeLabel(row.ts,isDemo())+'\n'+series.map(s=>s.label+': '+(row[s.key]==null?'—':options.percent?fmt(row[s.key]*100,1)+'%':fmt(row[s.key],2))).join('\n'));});hit.addEventListener('pointerleave',hideTip);}
}
const tooltip=document.createElement('div');tooltip.className='chart-tip';tooltip.hidden=true;document.body.append(tooltip);
function showTip(event,text){tooltip.textContent=text;tooltip.hidden=false;tooltip.style.left=Math.min(event.clientX+12,innerWidth-220)+'px';tooltip.style.top=Math.max(8,event.clientY-75)+'px';}
function hideTip(){tooltip.hidden=true;}
function drawFlow(report){
 const fills=report.fills||[],container=$('flow-map');if(!fills.length){container.innerHTML='<div class="empty-chart">No simulated fills in this recording. Market updates are not fills.</div>';return;}
 const visible=fills.slice(-500),w=1000,h=320,cx=500,cy=159,radius=123;
 let out=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Schematic execution map of ${visible.length} recorded simulated fills"><defs><radialGradient id="halo"><stop stop-color="#6dabc4" stop-opacity=".14"/><stop offset="1" stop-color="#142437" stop-opacity="0"/></radialGradient></defs><ellipse cx="${cx}" cy="${cy}" rx="235" ry="147" fill="url(#halo)"/>`;
 for(const r of [radius,radius*.72,radius*.42])out+=`<ellipse cx="${cx}" cy="${cy}" rx="${r}" ry="${r*.82}" fill="none" stroke="#253c51" stroke-dasharray="2 5"/>`;
 out+=`<path d="M215 80C350 80 320 159 500 159M785 242C650 242 680 159 500 159" fill="none" stroke="#496c6c" stroke-width="1"/><circle cx="215" cy="80" r="6" fill="#6debb2"/><circle cx="785" cy="242" r="6" fill="#f17c8b"/><text x="195" y="55" class="outcome-label" text-anchor="end" fill="#6debb2">UP</text><text x="805" y="267" class="outcome-label" fill="#f17c8b">DOWN</text>`;
 visible.forEach((fill,i)=>{const a=i*2.3999632297,rr=29+Math.sqrt((i+1)/visible.length)*(radius-20),x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr*.82,color=fill.outcome==='Up'?'#6debb2':'#f17c8b',node=Math.min(6,1.6+Math.sqrt(Number(fill.shares))*.43);const anchor=fill.outcome==='Up'?{x:215,y:80}:{x:785,y:242};out+=`<path d="M${anchor.x} ${anchor.y}Q${cx} ${cy} ${x.toFixed(2)} ${y.toFixed(2)}" fill="none" stroke="${color}" stroke-opacity=".065"/><circle class="fill-node" data-index="${i}" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="${node}" fill="${color}" fill-opacity=".85" stroke="${color}"/>`;});
 const p=report.portfolio;out+=`<rect x="432" y="130" width="136" height="58" rx="8" fill="#0d1724" fill-opacity=".94" stroke="#466078"/><text x="500" y="150" text-anchor="middle">COMPLETE SETS</text><text x="500" y="174" text-anchor="middle" class="big-label">${fmt(p.paired_shares,1)}</text><text x="155" y="115" text-anchor="middle">${fills.filter(f=>f.outcome==='Up').length} fills</text><text x="845" y="212" text-anchor="middle">${fills.filter(f=>f.outcome==='Down').length} fills</text><text x="65" y="230">UP RESIDUAL</text><text x="65" y="253" class="big-label">${fmt(p.residual_up,2)}</text><text x="820" y="66">DOWN RESIDUAL</text><text x="820" y="91" class="big-label">${fmt(p.residual_down,2)}</text></svg>`;
 container.innerHTML=out;container.querySelectorAll('.fill-node').forEach(node=>{const f=visible[Number(node.dataset.index)];node.addEventListener('pointermove',e=>showTip(e,`${f.outcome} · ${f.mode}\n${fmt(f.shares)} shares @ ${fmt(Number(f.price)*100)}¢\n${timeLabel(f.ts,isDemo())}`));node.addEventListener('pointerleave',hideTip);});
}
function renderBook(){const book=snapshot?.books?.[bookSide];if(!book)return;const max=Math.max(1,...book.asks.map(r=>Number(r[1])),...book.bids.map(r=>Number(r[1])));for(const [id,levels,type] of [['asks',book.asks.slice(0,4).reverse(),'ask'],['bids',book.bids.slice(0,4),'bid']]){$(id).innerHTML=levels.length?levels.map(([price,size])=>`<div class="book-row ${type}"><i style="width:${Math.min(100,Number(size)/max*100)}%"></i><span>${fmt(Number(price)*100)}¢</span><span>${fmt(size,1)}</span><span>${money(Number(price)*Number(size))}</span></div>`).join(''):'<div class="empty-chart">No levels available</div>';}
 set('book-spread',book.asks.length&&book.bids.length?fmt((Number(book.asks[0][0])-Number(book.bids[0][0]))*100)+'¢':'—');}
function renderLedger(){const all=snapshot?.report?.fills||[],rows=all.filter(f=>fillFilter==='All'||f.outcome===fillFilter);$('trade-rows').innerHTML=rows.length?rows.slice(-200).reverse().map(f=>`<tr><td>${timeLabel(f.ts,isDemo())}</td><td class="${f.outcome==='Up'?'green':'red'}">${esc(f.outcome)}</td><td>${fmt(Number(f.price)*100)}¢</td><td>${fmt(f.shares)}</td><td>${money(Number(f.shares)*Number(f.price))}</td><td class="muted">${esc(f.mode)}</td></tr>`).join(''):'<tr><td colspan="6">No fills for this selection</td></tr>';set('ledger-count',`${rows.length} ${fillFilter==='All'?'total':fillFilter} fills · latest ${Math.min(rows.length,200)} shown · simulated`);}
function render(){const r=snapshot?.report;if(!r){set('notice',snapshot?.error||'Connecting to the public feeds…');return;}const p=r.portfolio,h=snapshot.history||[],last=h.at(-1),demo=isDemo();
 set('asset-title',r.market.slug.split('-')[0].toUpperCase());set('market-name',r.market.slug);set('source-label',demo?'SYNTHETIC DEMO':'LIVE FEED RECORDING');set('run-status',snapshot.status.toUpperCase());set('capture-label',last?(demo?`Demo interval ${timeLabel(last.ts,true)}`:`Captured ${timeLabel(last.ts)} UTC`):'No observations');
 $('notice').className='notice'+(demo?'':' live');set('notice',demo?'Synthetic demo · All prices, fills and P&L in this run are simulated. This is not the advertised trader’s account.':'Public market data · Order fills and portfolio P&L below are paper simulations. Real wallet orders appear only in the wallet panel.');
 const error=snapshot.error||snapshot.feed_errors?.join(' · ');$('error').hidden=!error;if(error)set('error',error);
 set('pnl-value',signed(p.realized_pnl??p.conservative_mark_pnl));$('pnl-value').style.color=Number(p.realized_pnl??p.conservative_mark_pnl)<0?'var(--red)':'var(--green)';set('pnl-detail',p.resolved?'Resolved simulated P&L':'Conservative simulated mark');set('pnl-basis',p.resolved?'RESOLVED / PAPER':'MARKED / PAPER');
 set('cash-value',money(p.cash));set('fills-value',String(p.fills));set('cost-value',money(p.total_cost));set('fee-value',money(p.fees));set('spot-value',money(last?.spot));set('strike-value','Price to beat '+money(r.market.strike));set('spot-feed',demo?'SYNTHETIC':(r.spot_source||'WAITING').replace('polymarket_','').toUpperCase());set('period-label',h.length?`${timeLabel(h[0].ts,demo)} — ${timeLabel(h.at(-1).ts,demo)}${demo?' elapsed':' UTC'}`:'No history');set('q-up',r.probability_up==null?'—':fmt(r.probability_up*100,1)+'%');set('q-down',r.probability_up==null?'—':fmt((1-r.probability_up)*100,1)+'%');
 set('up-residual',fmt(p.residual_up));set('down-residual',fmt(p.residual_down));set('paired-value',fmt(p.paired_shares));const maximum=Math.max(1,Number(p.residual_up),Number(p.residual_down),Number(p.paired_shares));for(const [id,value] of [['up-bar',p.residual_up],['down-bar',p.residual_down],['paired-bar',p.paired_shares]])$(id).style.width=(Number(value)/maximum*100)+'%';set('imbalance',fmt(p.inventory_imbalance*100,1)+'%');set('pair-cost',p.average_pair_cost==null?'—':fmt(Number(p.average_pair_cost)*100)+'¢');set('net-value',fmt(Number(p.residual_up)-Number(p.residual_down))+' NET SHARES');set('loss-limit',money(r.config.max_loss));set('spend-limit',money(r.config.max_market_spend));
 const notional=r.fills.reduce((sum,f)=>sum+Number(f.shares)*Number(f.price),0);set('flow-notional',money(notional));set('paired-pnl',signed(p.paired_terminal_pnl));set('average-fill',money(p.average_trade_dollars));set('event-count',`${r.events.toLocaleString()} received events · ${r.fills.length} simulated fills`);
 chart('pnl-spark',h,[{key:'pnl',color:'#6debb2',label:'P&L'}],{spark:true,area:true});chart('spot-chart',h,[{key:'spot',color:'#6debb2',label:'Spot'}],{digits:2,area:true});chart('prob-chart',h,[{key:'q',color:'#6debb2',label:'Model Up'},{key:'up_ask',color:'#76a8e8',label:'Up ask',dash:true}],{min:0,max:1,fixed:true,percent:true});chart('exposure-chart',h,[{key:'net',color:'#6debb2',label:'Net shares'},{key:'paired',color:'#eebf68',label:'Complete sets',dash:true}]);chart('equity-chart',h,[{key:'pnl',color:'#6debb2',label:'Mark P&L'}],{area:true});drawFlow(r);renderBook();renderLedger();
 const actions=r.actions.slice(-10).reverse();$('activity').innerHTML=actions.length?actions.map(a=>`<span>${timeLabel(a.ts,demo)} <b>${esc(a.action.replaceAll('_',' '))}</b> ${esc(a.side||'')} ${a.price?fmt(Number(a.price)*100)+'¢':''}</span>`).join(''):'<span>No strategy actions yet. The model waits for valid, fresh data.</span>';set('order-count',`${r.open_orders} OPEN AT CAPTURE`);set('provenance',snapshot.provenance.recording+' · '+(demo?'synthetic':'public feeds'));
 $('stop-run').hidden=!['connecting','running','stopping'].includes(snapshot.status);$('stop-run').disabled=snapshot.status==='stopping';
}
async function loadRuns(){const data=await api('/api/runs');const select=$('run-select');select.innerHTML=data.runs.map(r=>`<option value="${esc(r.id)}">${esc(r.id)}${r.source.includes('synthetic')?' · demo':''}</option>`).join('');if(!data.runs.some(r=>r.id===current))current=data.runs[0]?.id||'demo';select.value=current;}
async function refresh(){if(polling)return;polling=true;try{snapshot=await api('/api/run?run='+encodeURIComponent(current));render();}catch(e){$('error').hidden=false;set('error',e.message);}finally{polling=false;}}
$('run-select').addEventListener('change',()=>{current=$('run-select').value;snapshot=null;refresh();});$('refresh').addEventListener('click',async()=>{await loadRuns();await refresh();});$('export').addEventListener('click',async()=>{try{const data=await api('/api/export?run='+encodeURIComponent(current)),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=current+'-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){set('error',e.message);$('error').hidden=false;}});
document.querySelectorAll('[data-book]').forEach(button=>button.addEventListener('click',()=>{bookSide=button.dataset.book;document.querySelectorAll('[data-book]').forEach(b=>b.classList.toggle('selected',b===button));renderBook();}));document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{fillFilter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('selected',b===button));renderLedger();}));
document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.close).close()));$('new-run').addEventListener('click',()=>$('shadow-dialog').showModal());$('shadow-form').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{const form=new FormData(event.target),data=await api('/api/shadow',{slug:form.get('slug'),strike:Number(form.get('strike')),seconds:Number(form.get('seconds'))});current=data.id;await loadRuns();$('shadow-dialog').close();await refresh();}catch(e){set('shadow-error',e.message);}finally{button.disabled=false;}});$('stop-run').addEventListener('click',async()=>{try{await api('/api/stop',{run:current});await refresh();}catch(e){set('error',e.message);$('error').hidden=false;}});
function openWallet(){$('wallet-dialog').showModal();} $('wallet-open').addEventListener('click',openWallet);$('rail-wallet').addEventListener('click',openWallet);
$('connect-wallet').addEventListener('click',async()=>{set('wallet-message','Waiting for your browser wallet…');$('connect-wallet').disabled=true;try{const bridge=await import('/wallet.js');wallet=await bridge.connectWallet($('account-wallet').value.trim());set('wallet-address',wallet.address.slice(0,8)+'…'+wallet.address.slice(-6));set('wallet-open','◈ '+wallet.address.slice(0,6)+'…'+wallet.address.slice(-4));set('wallet-message','Connected. Real orders require their own review and signature.');$('disconnect-wallet').hidden=false;$('place-real').disabled=false;$('real-refresh').disabled=false;$('cancel-real').disabled=false;await realRefresh();}catch(e){set('wallet-message',e.message);}finally{$('connect-wallet').disabled=false;}});
$('disconnect-wallet').addEventListener('click',()=>{wallet?.disconnect();wallet=null;set('wallet-address','Not connected');set('wallet-open','◈ Connect wallet');set('wallet-message','Disconnected. Existing exchange orders remain open until canceled.');$('disconnect-wallet').hidden=true;for(const id of ['place-real','real-refresh','cancel-real'])$(id).disabled=true;});
for(const id of ['real-price','real-size'])$(id).addEventListener('input',()=>set('real-cost',money(Number($('real-price').value)*Number($('real-size').value))));
async function realRefresh(){if(!wallet)return;try{const orders=await wallet.openOrders();$('real-orders').innerHTML=orders.length?orders.map(o=>`<div class="real-order"><span>${esc(o.id)}<br><span class="muted">${esc(o.side)} · ${esc(o.price)} · ${esc(o.status)}</span></span><button data-cancel="${esc(o.id)}">Cancel</button></div>`).join(''):'No open real orders.';$('real-orders').querySelectorAll('[data-cancel]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await wallet.cancel(b.dataset.cancel);await realRefresh();}catch(e){set('real-error',e.message);b.disabled=false;}}));}catch(e){set('real-error',e.message);}}
$('real-refresh').addEventListener('click',realRefresh);$('cancel-real').addEventListener('click',async()=>{if(!wallet)return;$('cancel-real').disabled=true;try{await wallet.cancelAll();set('wallet-message','Cancellation requested. Refreshing exchange state…');await realRefresh();}catch(e){set('real-error',e.message);}finally{$('cancel-real').disabled=false;}});
$('real-order-form').addEventListener('submit',async event=>{event.preventDefault();if(!wallet)return;set('real-error','');$('place-real').disabled=true;try{const result=await wallet.place({slug:$('real-slug').value.trim(),outcome:$('real-outcome').value,price:$('real-price').value,size:$('real-size').value,confirmed:$('real-confirm').checked});set('wallet-message','Exchange response: '+result.orderId+' · '+result.status);$('real-confirm').checked=false;await realRefresh();}catch(e){set('real-error',e.message);}finally{$('place-real').disabled=!wallet;}});
setInterval(()=>{set('utc',new Date().toLocaleTimeString('en-GB',{timeZone:'UTC'})+' UTC');if(!document.hidden)refresh();},2000);let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(render,100);});loadRuns().then(refresh).catch(e=>{set('error',e.message);$('error').hidden=false;});

$('funding-load').addEventListener('click',async()=>{try{const data=await api('/api/funding-assets');$('funding-token').innerHTML=data.assets.map(a=>`<option value="${esc(a.token.address)}">${esc(a.token.symbol)} ? ${esc(a.token.address)} ? min $${esc(a.minCheckoutUsd)}</option>`).join('');set('funding-result',data.assets.length?'Current supported assets loaded. Enter an amount and your trading wallet.':'No supported BNB tokens returned.');}catch(e){set('funding-result',e.message);}});
$('funding-form').addEventListener('submit',async event=>{event.preventDefault();event.submitter.disabled=true;try{const data=await api('/api/funding-quote',{token:$('funding-token').value,amount:$('funding-amount').value,recipient:$('funding-recipient').value.trim()}),q=data.quote;set('funding-result',`Quote only ? ${$('funding-amount').value} ${data.sourceToken.symbol} on BNB ? Polygon pUSD. Estimated output ${money(q.estOutputUsd)} ? total impact ${money(q.estFeeBreakdown.totalImpactUsd)} ? minimum received ${q.estFeeBreakdown.minReceived} ? about ${Math.ceil(q.estCheckoutTimeMs/1000)} sec. Destination: ${data.request.recipientAddress}. Quote ${q.quoteId}. Refresh before funding; complete the deposit in Polymarket.`);}catch(e){set('funding-result',e.message);}finally{event.submitter.disabled=false;}});
